.github/workflows/gradle-publish.yml
.gitmodules
server/build.gradle

CI/CD 적용을 위한 코드 변경
유의해서 봐야할 커밋
- build.gradle : submodule 적용 코드
- gradle.yml : submodule 적용 및 secret

[feat -> dev] 서버 CI/CD 적용

---

.github/workflows/gradle-publish.yml

CODE_DEPLOY_DEPLOYMENT_GROUP_NAME 오타 수정

#3 - gradle.yml 오타 수정

---

.github/workflows/gradle-publish.yml

CODE_DEPLOY_DEPLOYMENT_GROUP_NAME 오타 수정

#3 - gradle-publish.yml update

---

server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java

[BE] cors 엔드포인트 추가

---

.github/workflows/client-deploy.yml

fe_develop 브렌치에 푸시가 발생하면,
./client 하위 내용을 빌드 후 S3 버킷으로 전송하도록 작성

#10 - client-deploy.yml 작성

---

.github/workflows/client-deploy.yml

#10 클라이언트 ci/cd 테스트 2

---

.github/workflows/client-deploy.yml

#10 클라이언트 ci/cd 테스트 3

---

.github/workflows/client-deploy.yml

Upload To S3에서 ./dist -> ./build로 변경

#10 클라이언트 ci/cd 테스트 4

---

.github/workflows/client-deploy.yml

#10 - .env 작성 코드 삽입

---

client/src/Components/Main/Boards/Board.jsx
client/src/Components/Main/Boards/Boards.jsx
client/src/Components/Main/Carousels/Carousel.jsx
client/src/Components/Main/Carousels/CarouselItemList.jsx
client/src/Components/Main/Carousels/Item.jsx
client/src/Components/Main/Popups/Calendar.jsx
client/src/Components/Main/Popups/DatePopup.jsx
client/src/Components/Main/Popups/ListItem.jsx
client/src/Components/Main/Popups/LocationPopup.jsx
client/src/Components/Main/Popups/Overlay.jsx
client/src/Pages/Home.jsx
client/src/index.css

메인페이지 렌더링 이슈 관련 코드 수정
주요 커밋 )
- 캐러셀 코드 수정
- 커뮤니티 게시글 표시 관련 수정
- 팝업이 표시되었을 때에는 뒷 페이지와 상호작용 하지 않도록 css 수정 (index.css)
- 지역, 날짜 컴포넌트 모바일 뷰 관련 css 수정 (Calendar 컴포넌트 내에 다수 CSS 수정이 있었으니, Calendar 컴포넌트를 단독으로 불러와 사용할 때 이를 참고하여 수정 필요)

[Feat -> Dev/fe]  메인페이지 관련 코드 수정

---

client/src/Components/Main/Carousels/Carousel.jsx
client/src/index.css

웹 폰트의 로딩 속도 때문에, CSS transition이 처음 동작할 때 리소스가 적은 기기일 경우 애니메이션이 버벅거리는 현상 발생 
index.css 에서 Pretendard 폰트 import 방식을 변경

[Feat-> Dev/fe] 캐러셀 성능 개선

---

server/src/test/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilterTest.java

ec2 에러 메세지를 보기 힘든 관계로 에러/인포로 로그를 나눠서 파일로 저장함

[feat ->be/dev] #36 로깅

---

server/src/test/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilterTest.java

Reverts indiego-project/indiego#45

Revert "[feat ->be/dev] #36 로깅"

---

client/public/index.html
client/src/Components/Search/KaKaoMap.jsx
client/src/styles/MarkerOverlay.css
client/src/utils/createMarker.js
client/src/utils/useDebounce.js

카카오맵 관련 해서 발생하던 버그 들을 수정
- 더 이상 마커를 클릭 할 때마다 팝업이 중복으로 생성되지 않습니다.
- 더 이상 마커에 호버 할 때 표시되던 팝업이 자리를 이탈하지 않습니다.
- 이제 검색 후 검색 아이템을 눌렀을 때 자동으로 해당 마커의 팝업이 표시됩니다.
- fetching 이벤트에 debounce를 걸어서, 연속으로 이벤트가 발생할 때는 데이터가 fetching 되지 않습니다.
develop 클라이언트 서버 환경에서도 카카오맵을 동작하게 하기 위해서, index.html 에 존재하는 카카오맵 app 키를 수정하였습니다.
(혹시, 이 때문에 작동이 제대로 안되는 기능이 생겨서 app key가 필요하면 디스코드에 올리도록 하겠습니다.)

[Feat -> Dev/fe] 카카오맵 관련 코드 수정

---

client/src/App.css
client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
client/src/Pages/Tickets/TicketsDetail.jsx

* 공연 상세 페이지에 캘린더 컴포넌트를 추가할 자리를 만들면서 레이아웃 일부 수정 
*  css 작업만 진행하여 코드 리뷰 필요없이 바로 merge해도 될 것 같다고 판단

[feat -> Dev/fe] 공연 상세 페이지 레이아웃 일부 수정

---

server/build.gradle
server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentFailDto.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentResponseDto.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentSuccessCardDto.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/dto/PaymentSuccessDto.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/Payment.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/entity/PaymentStatus.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/repository/PaymentRepository.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java
server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java

- PaymentController, PaymentService 작성 : 결제 요청, 성공, 실패에 대한 API 기능 구현에 대한 코드
- 결제 DTO 작성 & Payment 수정, PaymentConfig 수정, PaymentFailDto 작성 : 결제 엔티티 및 요청, 응답 dto 정보 작성, PaymentSuccessDto는 추후 사용할 데이터만 응답하도록 회의 후 수정
전반적으로 결제를 위한 코드들을 작성하였습니다.
Service, Controller, DTO 코드들이 서로 연관되어 있기 때문에 한 번에 커밋, 푸시한 내용이 많습니다..!

[Feat -> Dev/be] 결제 Config, Status 작성

---

.gitmodules

Reverts indiego-project/indiego#61

Revert "[feat/be -> be/dev]서브모듈 추가"

---

client/src/Pages/Login.jsx

오류 메시지를 추가한 것 외에는 거의 바뀐 부분이 없어 따로 approve 받지 않고 merge 하겠습니다!

[feat -> Dev/fe] 잘못된 회원 유형으로 로그인 시 오류 처리 추가함

---

server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminController.java

[feat -> be/dev] #39 - 어드민 댓글 조회

---

server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminController.java
server/src/main/java/codestates/frogroup/indiego/domain/admin/AdminServiceImpl.java
server/src/main/java/codestates/frogroup/indiego/domain/admin/Certification.java
server/src/main/java/codestates/frogroup/indiego/domain/admin/CertificationServiceImpl.java

오류수정
- 증명 상태값 변경
- 권한 변경된 멤버 로그인

[feat/be -> dev/be] #39 - 어드민 기능 에러 수정

---

client/src/Components/TicketsDetail/SelectTicketDateCalendar.jsx
client/src/Pages/Tickets/TicketsDetail.jsx

*  예매 불가 상태일 때 레이아웃 / 반응형 레이아웃 추가
*  css 작업만 진행하여 코드 리뷰 필요없이 바로 merge해도 될 것 같다고 판단

[feat -> Dev/fe] 공연 상세 페이지 레이아웃 2차 수정 

---

server/src/main/java/codestates/frogroup/indiego/domain/member/dto/MemberDto.java
server/src/main/java/codestates/frogroup/indiego/domain/member/mapper/MemberMapper.java

- 멤버 조회 response에 certificationId 추가

[feat/ve -> dev/be] #39 - 어드민 기능 수정

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/config/PaymentConfig.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/controller/PaymentController.java
server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

- PaymentConfig : URL 변경
- PaymentController : 리다이렉트 URL 삭제
- PaymentService : 결제 승인 파라미터 변경

[Feat -> Dev/be] 결제 승인 요청 파라미터 수정 및 리다이렉트 URL 제거

---

server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowListDto.java
server/src/main/resources/graphql/schema.graphqls

1. getShow() 공연이미지 오류, Address 오류 수정

[Feat -> Dev/br] Tag 오류 수정

---

server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java
server/src/main/java/codestates/frogroup/indiego/global/logging/MDCLoggingFilter.java
server/src/main/resources/logback-spring.XML

[Feat/be -> dev/be] #36 logging

---

server/src/main/resources/logback-spring.XML

[feat/be -> dev/be] #36 로깅

---

server/src/main/resources/logback-spring.XML

[feat/be -> dev/be]#36 로깅

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

- 공연예약 반영 로직 수정
- 공연 예약 API 호출 시 발생하는 서버 에러 문제 수정
결제 연동 테스트 진행

[Feat -> Dev/be] requestPaymentAccept 수정

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

공연예약 반영 로직 수정
공연 예약 API 호출 시 발생하는 서버 에러 문제 수정
결제 연동 테스트 진행

[Feat -> Dev/be] requestPaymentAccept 수정 2

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

공연예약 반영 로직 수정
공연 예약 API 호출 시 발생하는 서버 에러 문제 수정
결제 연동 테스트 진행

[Feat -> Dev/be] requestPaymentAccept 수정 3

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

공연예약 반영 로직 수정
공연 예약 API 호출 시 발생하는 서버 에러 문제 수정
결제 연동 테스트 진행

[Feat -> Dev/be] requestPaymentAccept 수정 4

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

유의해서 봐야할 커밋
공연예약 반영 로직 수정
공연 예약 API 호출 시 발생하는 서버 에러 문제 수정
배경
결제 연동 테스트 진행

[Feat -> Dev/be] requestPaymentAccept 수정 5

---

server/src/main/java/codestates/frogroup/indiego/domain/show/entity/Show.java

[Feat -> Dev/be] requestPaymentAccept 수정 6

---

server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java

cross origin 허용 도메인 추가
개발 환경 도메인 추가됨에 따라 설정 변경

#115 - 개발환경 도메인 cross origin 수정

---

.github/workflows/client-deploy.yml

#96 - 클라이언트 CI/CD 경로 수정
클라이언트 CI/CD 버킷 수정

[Feat -> Dev/fe] HTTPS 적용을 위한 깃액션 시크릿 및 버킷 이름 수정

---

server/src/main/java/codestates/frogroup/indiego/domain/payment/service/PaymentService.java

https 적용 후 내부 api 호출 경로로 변경
클라이언트 - 서버 https 적용

[Feat -> Dev/be] PaymentService 내부 api 호출 경로 변경

---

server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java

시큐리티 www.devindiego.stie cors 허용

[Feat -> Dev/be] 시큐리티 cross origin 설정에 https 도메인 추가2

---

client/.eslintrc.json
client/prettierrc.json
client/src/Components/Admin/List.jsx

퍼포머 승인 / 거절 시 API 요청이 가지 않는 오류 발생
관련 코드를 수정하여 버그를 해결했습니다.

[Feat -> Dev/fe] 어드민 관련 퍼포머 승인 / 거절 버그 수정

---

client/public/index.html
client/src/Components/Ticktes/CardItem.jsx
client/src/Components/Ticktes/Create/SelectedTag.jsx
client/src/Components/Ticktes/Create/TagSelect.jsx
client/src/Components/Ticktes/ItemList.jsx
client/src/Pages/Tickets/TicketsCreate.jsx
client/src/Pages/Tickets/TicketsDetail.jsx

- 태그 갯수에 따라 페이지 레이아웃이 꺠져 보이는 버그 발생
- 태그 작성 / 수정 시 태그 갯수 제한 없이 적용 가능한 문제점
- 태그 갯수 최대 3개 까지(태그 내용이 많이 긴 상황에 따라, 최대 4개까지 보여주기로 했던 사항 반영 불가) 사용자에게 노출하고 이후 ... 표시
- 태그 작성 / 수정 시 태그 갯수를 최대 7개 만큼 작성 가능하고, 이를 초과할 시 사용자에게 알림

[Feat -> Dev/fe] 공연 태그 관련 레이아웃 수정 및 유효성 적용

---

server/src/main/resources/logback-spring.xml

- 단위 30일 ->1 일
- 하위레벨 로그도 남기도록 수정

[feat -> be] #128 로깅 파일 수정

---

server/src/main/java/codestates/frogroup/indiego/config/BatchConfig.java
server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java

[feat -> be] #127 스프링배치
